### ISSUE TITLE
유저 칭호작업 하기

### ISSUE THREAD

**Issue by laonmofu** [laonmofu/Mofu-Life#4]
Render Queue...
- [x] 1. 유설님 (카나데? 나츠?)
- [x] 2. 해담님 (🍙?)
- [x] 3. 슈플님 (키보드 크래셔
- [ ] 4. 매콤님 (어라라?)

**Comment by SWREI** [comment]
+1

**Comment by laonmofu** [comment]
끝낸지오조오억년됨
