### ISSUE TITLE
같이 라멘 먹기

### ISSUE THREAD

**Issue by SWREI** [laonmofu/Mofu-Life#5]
서울오실?

**Comment by laonmofu** [comment]
헉 언제요 저 좀 괜찮은 라멘집 알고는 있거든요...
닭이 좋으세요 돼지가 좋으세요?

**Comment by SWREI** [comment]
> 헉 언제요 저 좀 괜찮은 라멘집 알고는 있거든요... 닭이 좋으세요 돼지가 좋으세요?

저는 사실 닭도 돼지도 잘 먹는 잡식동물이에요
그럼 내일로 합시다 (?)

**Comment by laonmofu** [comment]
뭣 내일요...?
조속히 디엠드리겠습니다

**Comment by Hoto-Cocoa** [comment]
저도 참여합니다

Cc. @yom21c1020

**Comment by SWREI** [comment]
급작스럽게 늘어난 사람
